Feature/cluster datasource name
nutanix/terraform-provider-nutanix pull request #100
Opened 2020-03-17 17:11 UTC by yannickstruyf3

One of my clients requested the possibility to search clusters by name via the data sources. This code adds this functionality to the existing data_source_nutanix_cluster.go file.

Acceptance test included.

2020-03-18 21:55 UTC, yannickstruyf3 commented
@marinsalinas rebased master

2020-03-19 14:39 UTC, marinsalinas requested changes
Almost done, just few comments.

2020-03-19 14:39 UTC, marinsalinas commented on nutanix/data_source_nutanix_cluster.go
> +				// Required: true,
Could you remove this attribute and add Computed: true.

2020-03-19 14:39 UTC, marinsalinas commented on nutanix/data_source_nutanix_cluster.go
> +				Optional:      true,
Could you add Computed:true as well.

2020-03-19 14:39 UTC, marinsalinas commented on nutanix/data_source_nutanix_cluster.go
> +				// Required: true,
also add `ConflictsWith: []string{"cluster_name"}` in order to raise an error when both values are set.

2020-03-19 14:39 UTC, marinsalinas commented on nutanix/data_source_nutanix_cluster.go
> +func findClusterByName(conn *v3.Client, name string) (*v3.ClusterIntentResponse, error) {
Nice catch, isn't there any way to find a cluster by name through the API?, If not we can keep like this and create a ticket to the API Tram to support this.

2020-03-19 14:39 UTC, marinsalinas commented on nutanix/data_source_nutanix_cluster.go
> +		// clusterEntitiesMetadata := &v3.DSMetadata{}
please remove all the unnecessary comments.

2020-03-19 15:34 UTC, marinsalinas requested changes
Just remove the unnecessary logs please.

2020-03-19 15:34 UTC, marinsalinas commented on nutanix/resource_nutanix_virtual_machine.go
> +	log.Printf("=====")
could you remove unnecessary logs?

2020-03-19 15:34 UTC, marinsalinas commented on nutanix/resource_nutanix_virtual_machine.go
> +	log.Printf("=====")
same here

2020-03-19 17:15 UTC, marinsalinas approved these changes

2020-03-19 17:15 UTC, merged