Improvement to create images using 'data_source_reference'
nutanix/terraform-provider-nutanix pull request #156
Opened 2020-07-06 18:45 UTC by kumarsarath588

* Improvement to create images using 'data_source_reference'

2020-11-17 18:01 UTC, marinsalinas commented
@kumarsarath588 can you add a test case and website documentation for this feature?

2022-02-17 08:05 UTC, siddharth-nutanix commented
@kumarsarath588 Can you rebase your PR with master and change the type from map to list with max items as 1 as Maps doesn't support inner nested schema ? 

Another option could be to use just TypeMap with 
`schema.Schema {
Elem: schema.TypeString,
}`
Check https://www.terraform.io/plugin/sdkv2/schemas/schema-types#typemap for more details.

2022-02-22 17:34 UTC, siddharth-nutanix requested changes

2022-02-22 17:34 UTC, siddharth-nutanix commented on nutanix/resource_nutanix_image.go
> +	if iok && pok && dsr {
What if only two values are provided ?
Then also we should raise error.

2022-02-22 17:34 UTC, siddharth-nutanix commented on nutanix/resource_nutanix_image.go
> +				Computed: true,
If the field is marked as "Computed" then we should ideally read its value in resourceNutanixImageRead().
It calls out to https://www.nutanix.dev/api_references/prism-central-v3/#/b3A6MjU1ODc1MTE-get-a-existing-image API. 
We can set this value in read function as well.

2025-05-15 11:00 UTC, GullapalliAkhil commented
This enhancement has been covered as part of this PR https://github.com/nutanix/terraform-provider-nutanix/pull/837, closing this.

2025-05-15 11:00 UTC, closed without merging