Removed volume_group documentations
nutanix/terraform-provider-nutanix pull request #160
Opened 2020-08-05 15:05 UTC by PacoDw

- Since the volume groups resource is not part of the Nutanix provider, it was removed

2020-08-05 21:18 UTC, coderGo93 approved these changes
LGTM

2020-08-05 21:34 UTC, marinsalinas requested changes
I think we can keep those files and just remove the link over this: https://github.com/terraform-providers/terraform-provider-nutanix/blob/master/website/nutanix.erb#L19

2020-08-06 14:18 UTC, PacoDw commented
Thanks, @marinsalinas it's better 👍

2020-08-06 15:54 UTC, marinsalinas approved these changes

2020-08-06 15:54 UTC, marinsalinas commented on website/nutanix.erb
> +<% end %>
just add trailing line please :)

2020-08-10 13:00 UTC, merged