WIP: fix disk_list
nutanix/terraform-provider-nutanix pull request #2
Opened 2018-10-14 16:10 UTC by simonfuhrer

Any subsequent changes to a virtual machine will cause the disks to be deleted. 

This PR fixes this problem.

2018-10-15 21:19 UTC, marinsalinas commented
@simonfuhrer do you have any configuration to see how this change works?

2018-10-16 18:35 UTC, simonfuhrer commented
@marinsalinas this change does not require any special configuration. It works as described in the docs 

it no longer deletes the disks if the name of the VM should be changed for example.

In the current release every change (or better every update request) causes the disks to be deleted.

2018-10-17 21:05 UTC, marinsalinas commented
@simonfuhrer I'm testing your work and the changes broke some tests.

First, some attributes need the VM turned off that's why we turn off the VM before updating and then turn on after that.

Also some acceptance test are failing after your changes.

Here is the log:

```hcl
testing.go:518: Step 0 error: After applying this step, the plan was not empty:

        DIFF:

        UPDATE: nutanix_virtual_machine.vm1
          disk_list.0.data_source_reference.#:      "0" => "1"
          disk_list.0.data_source_reference.0.kind: "" => "image"
          disk_list.0.data_source_reference.0.uuid: "" => "e3d1cfea-55e2-424b-8bb5-46bac816cc36"

        STATE:

        data.nutanix_clusters.clusters:
          ID = 5d66621a-11d1-43c1-8fe6-5a11e718dac1
          provider = provider.nutanix
          api_version = 3.1
          entities.# = 2
          entities.0.analysis_vm_efficiency_map.% = 5
          entities.0.analysis_vm_efficiency_map.bully_vm_num = 0
          entities.0.analysis_vm_efficiency_map.constrained_vm_num = 0
          entities.0.analysis_vm_efficiency_map.dead_vm_num = 9
          entities.0.analysis_vm_efficiency_map.inefficient_vm_num = 11
          entities.0.analysis_vm_efficiency_map.overprovisioned_vm_num = 2
          entities.0.api_version =
          entities.0.authorized_public_key_list.# = 0
          entities.0.build.% = 6
          entities.0.build.build_type = release
          entities.0.build.commit_date =
          entities.0.build.commit_id = 07dbff43ac5a9f4edcd0c7ce1dccbc25a1c098b5
          entities.0.build.full_version = el7.3-release-euphrates-5.6-stable-07dbff43ac5a9f4edcd0c7ce1dccbc25a1c098b5
          entities.0.build.short_commit_id = 07dbff
          entities.0.build.version = 5.6
          entities.0.ca_certificate_list.# = 0
          entities.0.categories.% = 0
          entities.0.certification_signing_info.% = 0
          entities.0.client_auth.% = 0
          entities.0.cluster_arch = X86_64
          entities.0.domain_server_credentials.% = 0
          entities.0.domain_server_name =
          entities.0.domain_server_nameserver =
          entities.0.enabled_feature_list.# = 3
          entities.0.enabled_feature_list.0 = PASSWORD_REMOTE_LOGIN_ENABLED
          entities.0.enabled_feature_list.1 = SHADOW_CLONES_ENABLED
          entities.0.enabled_feature_list.2 = NETWORK_FLOW_STATS_COLLECTOR_ENABLED
          entities.0.encryption_status = NOT_SUPPORTED
          entities.0.external_data_services_ip =
          entities.0.external_ip =
          entities.0.external_subnet = 172.0.0.0/255.0.0.0
          entities.0.gpu_driver_version =
          entities.0.http_proxy_list.# = 0
          entities.0.http_proxy_whitelist.# = 0
          entities.0.internal_subnet = 172.0.0.0/255.0.0.0
          entities.0.is_available = true
          entities.0.management_server_list.# = 0
          entities.0.masquerading_ip =
          entities.0.masquerading_port = 0
          entities.0.metadata.% = 7
          entities.0.metadata.creation_time = 0001-01-01 00:00:00 +0000 UTC
          entities.0.metadata.kind = cluster
          entities.0.metadata.last_update_time = 0001-01-01 00:00:00 +0000 UTC
          entities.0.metadata.name =
          entities.0.metadata.spec_hash =
          entities.0.metadata.spec_version = 0
          entities.0.metadata.uuid = 27db5fb2-2aa0-48c4-bd2a-2fccdb8fad36
          entities.0.name = test-jon-gcp
          entities.0.name_server_ip_list.# = 1
          entities.0.name_server_ip_list.0 = 8.8.8.8
          entities.0.nfs_subnet_whitelist.# = 0
          entities.0.nodes.# = 2
          entities.0.nodes.0.ip = 127.0.0.1
          entities.0.nodes.0.type = AHV
          entities.0.nodes.0.version =
          entities.0.nodes.1.ip = 172.16.1.4
          entities.0.nodes.1.type = AHV
          entities.0.nodes.1.version =
          entities.0.ntp_server_ip_list.# = 1
          entities.0.ntp_server_ip_list.0 = 8.8.8.8
          entities.0.operation_mode = NORMAL
          entities.0.owner_reference.% = 0
          entities.0.project_reference.% = 0
          entities.0.service_list.# = 1
          entities.0.service_list.0 = AOS
          entities.0.smtp_server_address.% = 0
          entities.0.smtp_server_credentials.% = 0
          entities.0.smtp_server_email_address =
          entities.0.smtp_server_proxy_type_list.# = 0
          entities.0.smtp_server_type =
          entities.0.software_map_ncc.% = 3
          entities.0.software_map_ncc.software_type = NCC
          entities.0.software_map_ncc.status = INSTALLED
          entities.0.software_map_ncc.version = ncc-3.5.1
          entities.0.software_map_nos.% = 3
          entities.0.software_map_nos.software_type = NOS
          entities.0.software_map_nos.status = INSTALLED
          entities.0.software_map_nos.version = 5.6
          entities.0.ssl_key_expire_datetime =
          entities.0.ssl_key_name =
          entities.0.ssl_key_signing_info.% = 0
          entities.0.ssl_key_type =
          entities.0.state = COMPLETE
          entities.0.supported_information_verbosity = BASIC_PLUS_CORE_DUMP
          entities.0.timezone = UTC
          entities.1.analysis_vm_efficiency_map.% = 0
          entities.1.api_version =
          entities.1.authorized_public_key_list.# = 0
          entities.1.build.% = 6
          entities.1.build.build_type = release
          entities.1.build.commit_date = 2018-08-02T00:29:56Z
          entities.1.build.commit_id = aedfa93d5ad7135f43097c0a3e3010d8f7c5e8ca
          entities.1.build.full_version = el7.3-release-euphrates-5.8.1-stable-aedfa93d5ad7135f43097c0a3e3010d8f7c5e8ca
          entities.1.build.short_commit_id = aedfa9
          entities.1.build.version = 5.8.1
          entities.1.ca_certificate_list.# = 0
          entities.1.categories.% = 0
          entities.1.certification_signing_info.% = 0
          entities.1.client_auth.% = 0
          entities.1.cluster_arch = X86_64
          entities.1.domain_server_credentials.% = 0
          entities.1.domain_server_name =
          entities.1.domain_server_nameserver =
          entities.1.enabled_feature_list.# = 2
          entities.1.enabled_feature_list.0 = PASSWORD_REMOTE_LOGIN_ENABLED
          entities.1.enabled_feature_list.1 = SHADOW_CLONES_ENABLED
          entities.1.encryption_status = NOT_SUPPORTED
          entities.1.external_data_services_ip =
          entities.1.external_ip =
          entities.1.external_subnet = 172.0.0.0/255.0.0.0
          entities.1.gpu_driver_version =
          entities.1.http_proxy_list.# = 0
          entities.1.http_proxy_whitelist.# = 0
          entities.1.internal_subnet = 172.0.0.0/255.0.0.0
          entities.1.is_available = true
          entities.1.management_server_list.# = 0
          entities.1.masquerading_ip =
          entities.1.masquerading_port = 0
          entities.1.metadata.% = 7
          entities.1.metadata.creation_time = 0001-01-01 00:00:00 +0000 UTC
          entities.1.metadata.kind = cluster
          entities.1.metadata.last_update_time = 0001-01-01 00:00:00 +0000 UTC
          entities.1.metadata.name =
          entities.1.metadata.spec_hash =
          entities.1.metadata.spec_version = 0
          entities.1.metadata.uuid = 706ff6fb-0415-4830-958e-c92302297420
          entities.1.name = Unnamed
          entities.1.name_server_ip_list.# = 1
          entities.1.name_server_ip_list.0 = 8.8.8.8
          entities.1.nfs_subnet_whitelist.# = 0
          entities.1.nodes.# = 0
          entities.1.ntp_server_ip_list.# = 1
          entities.1.ntp_server_ip_list.0 = 8.8.8.8
          entities.1.operation_mode = NORMAL
          entities.1.owner_reference.% = 0
          entities.1.project_reference.% = 0
          entities.1.service_list.# = 1
          entities.1.service_list.0 = PRISM_CENTRAL
          entities.1.smtp_server_address.% = 0
          entities.1.smtp_server_credentials.% = 0
          entities.1.smtp_server_email_address =
          entities.1.smtp [...]

2018-10-17 21:41 UTC, simonfuhrer commented
@marinsalinas 

Do you know which operation  requires a poweroff power on?

2018-10-17 22:35 UTC, marinsalinas commented
@simonfuhrer update VM requires in some attitudes @JonKohler, Do you know exactly which attributes require the VM turned off to update?.

2018-10-17 23:39 UTC, marinsalinas requested changes

2018-10-17 23:39 UTC, marinsalinas commented on nutanix/resource_nutanix_virtual_machine.go
> +	sold := make([]*v3.VMDisk, len(response.Status.Resources.DiskList))
You could keep this and return the fields ForceNew and the rest let them ForceNew as they were before, I think shouldn't delete the DiskList.

2019-01-25 21:23 UTC, JonKohler commented
It would be really interesting to try this again on Prism Central / Prism Element 5.10.0.2 or any of other releases mentioned in field advisory Field Advisory #0059, available here: https://portal.nutanix.com/#/page/static/fieldAdvisories

I have a sneaking suspicion this may be related to that. Might not be, but we should double check

2019-04-11 17:02 UTC, closed without merging