Add vCPU hard pinning
nutanix/terraform-provider-nutanix pull request #307
Opened 2021-11-19 12:36 UTC by basraayman

Added the option to allow hard pinning to be configured.

2022-01-19 07:05 UTC, siddharth-nutanix commented
/ok-to-test

2022-02-09 08:14 UTC, siddharth-nutanix approved these changes

2022-02-09 13:19 UTC, shreevari approved these changes

2022-02-10 08:43 UTC, siddharth-nutanix requested changes

2022-02-10 08:43 UTC, siddharth-nutanix commented on nutanix/resource_nutanix_virtual_machine.go
> +	d.Set("is_vcpu_hard_pinned", resp.Status.Resources.EnableCPUPinning)
```suggestion
	d.Set("is_vcpu_hard_pinned", utils.BoolValue(resp.Status.Resources.EnableCPUPinning))
```

2022-02-10 08:43 UTC, siddharth-nutanix commented on nutanix/resource_nutanix_virtual_machine.go
> +	d.Set("is_vcpu_hard_pinned", resp.Status.Resources.EnableCPUPinning)
@basraayman Can you check the above suggestion ? 
I feel we need to convert boolean pointer to boolean while setting the value to resource data.

2022-02-10 08:56 UTC, siddharth-nutanix commented on nutanix/resource_nutanix_virtual_machine.go
> +	d.Set("is_vcpu_hard_pinned", resp.Status.Resources.EnableCPUPinning)
My bad values do get set with boolean pointers as well.

2022-02-10 08:56 UTC, siddharth-nutanix approved these changes

2022-02-10 08:59 UTC, merged

2022-02-10 10:01 UTC, basraayman reviewed
All good, thank you. :)