Service groups address groups test cases
nutanix/terraform-provider-nutanix pull request #339
Opened 2022-02-10 15:39 UTC by abhimutant

Added serviceGroup and addressGroup testcases.

2022-02-10 15:43 UTC, abhimutant commented
/ok-to-test
>Acceptance test run status: failure
>

2022-02-10 18:23 UTC, siddharth-nutanix requested changes

2022-02-10 18:23 UTC, siddharth-nutanix commented on nutanix/resource_nutanix_service_group_test.go
> +package nutanix
Lets merge https://github.com/nutanix/terraform-provider-nutanix/pull/322 first.

2022-02-14 03:58 UTC, abhimutant commented
Closing this PR as #340 is raised for the same.

2022-02-14 03:58 UTC, closed without merging