Client SDK changes for foundation based bare metal provisioning
nutanix/terraform-provider-nutanix pull request #352
Opened 2022-02-21 14:40 UTC by bhatipradeep

Changes:

- Added a new foundation client with appropriate structs.
- Updated(Temporary) client_test.go as per changes in credentials struct, which now also have foundation related attributes.
- Updated config.go and provider.go for accomodating newly created foundation client and its requirements.

2022-02-21 15:03 UTC, siddharth-nutanix requested changes

2022-02-21 15:03 UTC, siddharth-nutanix commented on client/client.go
> +	httpBaseURL    = "http://%s/"
Can we use same base URL and make http / https dynamic by using boolean flag isHTTP?

2022-02-21 15:03 UTC, siddharth-nutanix commented on client/foundation/foundation_file_management_service.go
> +func (fileManagementOperations FileManagementOperations) ListNOSPackages() (*ListNOSPackagesResponse, error) {
```suggestion
func (fmo FileManagementOperations) ListNOSPackages() (*ListNOSPackagesResponse, error) {
```
Use smaller variable names as we already have type defined.

2022-02-21 15:03 UTC, siddharth-nutanix commented on client/foundation/foundation_file_management_service.go
> +func (fileManagementOperations FileManagementOperations) ListNOSPackages() (*ListNOSPackagesResponse, error) {
Make changes everywhere.

2022-02-21 15:03 UTC, siddharth-nutanix commented on client/foundation/foundation_file_management_service.go
> +	ctx := context.TODO()
pass context everywhere.

2022-02-21 15:03 UTC, siddharth-nutanix commented on client/foundation/foundation_file_management_service.go
> +	ctx := context.TODO()
make changes everywhere.

2022-02-21 15:03 UTC, siddharth-nutanix commented on nutanix/config.go
> +		FoundationURL:      fmt.Sprintf("%s:%s", c.FoundationEndpoint, c.FoundationPort),
Do we need FoundationURL as separate member of client.Credentials ?
Whenever we need the foundation URL we can always create it using endpoint and port.

2022-02-21 15:03 UTC, siddharth-nutanix commented on nutanix/provider.go
> +		"foundation_endpoint": "URL for foundation VM (eg. Foundation VM IP)",
```suggestion
		"foundation_endpoint": "endpoint for foundation VM (eg. Foundation VM IP)",
```

2022-02-22 02:40 UTC, bhatipradeep commented on client/foundation/foundation_api.go
> +	NodeImaging NodeImagingService
Done

2022-02-22 10:30 UTC, siddharth-nutanix approved these changes

2022-02-22 10:30 UTC, siddharth-nutanix commented on client/client.go
> +	protocol := "https"
lets move http / https in constants.

2022-02-22 10:30 UTC, siddharth-nutanix commented on client/client.go
> +	protocol := "https"
You can also create a method to figure out and construct a baseURL

2022-02-22 10:31 UTC, merged