Security rules with service group and address groups
nutanix/terraform-provider-nutanix pull request #384
Opened 2022-03-14 02:18 UTC by siddharth-kulshrestha

2022-03-15 08:59 UTC, siddharth-nutanix commented
/ok-to-test

2022-03-15 11:11 UTC, bhati-pradeep requested changes

2022-03-15 11:11 UTC, bhati-pradeep commented on nutanix/resource_nutanix_network_security_rule.go
> +func expandReferencePtr(reference map[string]interface{}) *v3.Reference {
Is this same as expandReference() helper ?

2022-03-15 11:11 UTC, bhati-pradeep commented on nutanix/resource_nutanix_network_security_rule.go
> +func flattenReferencesList(refs []*v3.Reference) []map[string]interface{} {
can we use flattenArrayReferenceValues() helper method ?

2022-03-16 16:23 UTC, siddharth-nutanix commented
/ok-to-test

2022-03-16 18:38 UTC, bhati-pradeep approved these changes

2022-03-17 05:08 UTC, siddharth-nutanix commented
/ok-to-test

2022-03-17 08:21 UTC, merged