Feat/m vpc
nutanix/terraform-provider-nutanix pull request #457
Opened 2022-06-03 07:32 UTC by Abhishekism9450

Added Resource for VPC:

- resource_nutanix_vpc

Added DataSources for VPC:

- data_source_nutanix_vpc
- data_source_nutanix_vpc_list

2022-06-13 07:50 UTC, siddharth-kulshrestha requested changes

2022-06-13 07:50 UTC, siddharth-kulshrestha commented on client/v3/v3_service.go
> +	//ctx := context.TODO()
Please remove this unwanted line of code.

2022-06-13 07:50 UTC, siddharth-kulshrestha commented on nutanix/data_source_nutanix_vpc.go
> +			// COMPUTED RESOURCES
Comp
```suggestion
			// Computed attributes
```

2022-06-13 07:50 UTC, siddharth-kulshrestha commented on nutanix/data_source_nutanix_vpc_list.go
> +			// COMPUTED RESOURCES
```suggestion
			// Computed attributes
```

2022-06-13 07:50 UTC, siddharth-kulshrestha commented on nutanix/resource_nutanix_vpc.go
> +	// if d.HasChange("external_subnet_list") {
Is this commented code required?

2022-06-14 07:17 UTC, Abhishekism9450 commented on nutanix/resource_nutanix_vpc.go
> +	// if d.HasChange("external_subnet_list") {
No. Removed the commented code.

2022-06-16 07:08 UTC, siddharth-kulshrestha approved these changes

2022-06-20 18:09 UTC, merged