Feat/m floating i ps
nutanix/terraform-provider-nutanix pull request #466
Opened 2022-06-20 18:29 UTC by Abhishekism9450

2022-06-23 15:31 UTC, siddharth-kulshrestha requested changes

2022-06-23 15:31 UTC, siddharth-kulshrestha commented on nutanix/data_source_nutanix_floating_ips.go
> +func dataSourceNutanixFloatingIPsCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
```suggestion
func dataSourceNutanixFloatingIPsRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
```

2022-06-23 15:31 UTC, siddharth-kulshrestha commented on nutanix/data_source_nutanix_floating_ips.go
> +func dataSourceNutanixFloatingIPs() *schema.Resource {
By file name it looks like a plural datasource but from implementation it looks like a singular datasource.

2022-06-23 15:31 UTC, siddharth-kulshrestha commented on nutanix/data_source_nutanix_floating_ips.go
> +func flattenStatusFIP(stat *v3.FIPDefStatus) []interface{} {
Please rename this struct to FloatingIPDefStatus.

2022-06-23 15:31 UTC, siddharth-kulshrestha commented on nutanix/provider.go
> +			"nutanix_floating_ips":                            dataSourceNutanixFloatingIPs(),
Both the datasource looks like plural.

2022-06-23 15:31 UTC, siddharth-kulshrestha commented on nutanix/data_source_nutanix_floating_ips_list.go
> +			"length": {
Do we need offset and length as part of the schema ? 
I guess in other datasources we iteratively fetch all the entities, combine them and populate the .tf file. 

Keeping offset and length in terraform file doesn't make sense to me. If you have any specific reasons for doing it we can discuss.

2022-06-23 15:31 UTC, siddharth-kulshrestha commented on nutanix/resource_nutanix_floating_ip.go
> +		Delay:      FipDelayTime,
Why do we have to use these global variables here ?

2022-06-23 15:31 UTC, siddharth-kulshrestha commented on nutanix/resource_nutanix_floating_ip.go
> +			"error waiting for floating ip (%s) to delete: %s", d.Id(), err)
```suggestion
			"error waiting for floating ip (%s) to delete: %s", d.Id(), err.Error())
```

2022-06-23 15:31 UTC, siddharth-kulshrestha commented on examples/floating_ip/main.tf
> +# create Floating IP with External Subnet UUID
datasource example is missing.

2022-06-23 15:31 UTC, siddharth-kulshrestha commented on nutanix/provider.go
> +			"nutanix_floating_ip":                      resourceNutanixFloatingIP(),
Documentation change is required.

2022-06-27 08:03 UTC, Abhishekism9450 commented on nutanix/data_source_nutanix_floating_ips_list.go
> +			"length": {
removed length and offset .

2022-06-27 08:05 UTC, Abhishekism9450 commented on nutanix/resource_nutanix_floating_ip.go
> +		Delay:      FipDelayTime,
yes, some constant numbers are magic numbers which are pre checked in PR.

2022-06-27 08:05 UTC, Abhishekism9450 commented on nutanix/provider.go
> +			"nutanix_floating_ip":                      resourceNutanixFloatingIP(),
noted.

2022-06-27 08:06 UTC, Abhishekism9450 commented on examples/floating_ip/main.tf
> +# create Floating IP with External Subnet UUID
created datasource examples .

2022-07-04 06:20 UTC, siddharth-kulshrestha approved these changes

2022-07-04 06:38 UTC, merged