Feat/era plugin
nutanix/terraform-provider-nutanix pull request #493
Opened 2022-09-19 11:26 UTC by Abhishekism9450

Resource for provision of database

2022-09-26 07:57 UTC, siddharth-kulshrestha requested changes

2022-09-26 07:57 UTC, siddharth-kulshrestha commented on nutanix/common_era_schema.go
> +		ForceNew:    true,
This schema is not getting used anywhere. 
Also, we have marked it as ForceNew. Make sure that the caller funcs calling this func don't provision the parent resources after changing the machine details.
Please check the behavior of Force new or make it as a parameter to this function.

2022-09-26 07:57 UTC, siddharth-kulshrestha commented on nutanix/common_era_schema.go
> +		Description: "sample description for time machine info",
change this

2022-09-26 07:57 UTC, siddharth-kulshrestha commented on nutanix/common_era_schema.go
> +		Description: "sample description for time machine info",
Please make the changes everywhere.

2022-09-26 07:57 UTC, siddharth-kulshrestha commented on nutanix/common_era_schema.go
> +func tryToConvertBool(v interface{}) (bool, bool) {
Can we use the same ConvToBool func ?

2022-09-28 11:33 UTC, Abhishekism9450 commented on nutanix/common_era_schema.go
> +func tryToConvertBool(v interface{}) (bool, bool) {
This func is no longer used. Removed it

2022-10-04 07:35 UTC, abhimutant commented
/ok-to-test era

2022-10-04 07:42 UTC, abhimutant commented
/ok-to-test era

2022-10-04 07:50 UTC, abhimutant commented
/ok-to-test era

2022-10-04 10:28 UTC, abhimutant commented
/ok-to-test pc

2022-10-07 05:30 UTC, abhimutant commented
/ok-to-test era

2022-10-07 05:37 UTC, abhimutant commented
/ok-to-test era

2022-10-07 08:19 UTC, abhimutant commented
/ok-to-test era

2022-10-11 12:06 UTC, siddharth-kulshrestha approved these changes

2022-10-11 12:11 UTC, merged