added import and snapshot name to Optional
nutanix/terraform-provider-nutanix pull request #561
Opened 2023-03-01 13:26 UTC by Abhishekism9450

2023-03-01 15:16 UTC, siddharth-kulshrestha approved these changes

2023-04-17 12:50 UTC, siddharth-kulshrestha approved these changes

2023-04-17 16:13 UTC, bhati-pradeep requested changes

2023-04-17 16:13 UTC, bhati-pradeep commented on nutanix/data_source_nutanix_ndb_profiles_available_ips_test.go
> +					resource.TestCheckResourceAttrSet("data.nutanix_ndb_network_available_ips.ips", "available_ips.0.id"),
can we check if multiple values are coming or not

2023-04-17 16:13 UTC, bhati-pradeep commented on nutanix/resource_nutanix_nbd_database_test.go
> +					resource.TestCheckResourceAttrSet(resourceNameDB, "time_machine.#"),
In file name it should be "_ndb_"

2023-04-17 20:05 UTC, Abhishekism9450 commented on nutanix/data_source_nutanix_ndb_profiles_available_ips_test.go
> +					resource.TestCheckResourceAttrSet("data.nutanix_ndb_network_available_ips.ips", "available_ips.0.id"),
Checked in PR #570 .

2023-04-18 03:07 UTC, bhati-pradeep approved these changes
LGTM

2023-04-18 06:41 UTC, abhimutant approved these changes

2023-04-18 06:41 UTC, merged