changed Port field to Optional
nutanix/terraform-provider-nutanix pull request #607
Opened 2023-06-14 07:08 UTC by Abhishekism9450

Making Port attribute to Optional.

2023-06-14 07:36 UTC, siddharth-kulshrestha requested changes

2023-06-14 07:36 UTC, siddharth-kulshrestha commented on client/karbon/karbon_private_registry_structs.go
>  	Cert     *string `json:"cert" mapstructure:"cert, omitempty"`
Please remove space between comma and omitempty.

2023-06-14 07:36 UTC, siddharth-kulshrestha commented on client/karbon/karbon_private_registry_structs.go
>  	Cert     *string `json:"cert" mapstructure:"cert, omitempty"`
In the whole file.

2023-06-14 07:41 UTC, Abhishekism9450 commented on client/karbon/karbon_private_registry_structs.go
>  	Cert     *string `json:"cert" mapstructure:"cert, omitempty"`
Done.

2023-06-14 07:45 UTC, siddharth-kulshrestha approved these changes

2023-06-14 08:24 UTC, merged

2023-06-15 00:07 UTC, kingsleyck commented
Thanks all, incredible turnaround.