Bugfix/power_state_mechanism
nutanix/terraform-provider-nutanix pull request #99
Opened 2020-03-17 12:56 UTC by yannickstruyf3

Fixed following bugs for client:
- Unable to use power_state_mechanism during initial provisioning
- When using guest customization, a CDrom drive is attached to the VM. Running a second Terraform apply causes an error due to the power state of the VM. Removing CDrom drives requires a powered off VM.

Kind regards

2020-03-18 21:42 UTC, marinsalinas commented
Could you update this branch from the latest version of the master?

2020-03-18 21:42 UTC, marinsalinas commented
does this close a specific GitHub issue?

2020-03-18 21:54 UTC, yannickstruyf3 commented
@marinsalinas rebased master branch

2020-03-19 17:19 UTC, marinsalinas requested changes
Please solve the conflicts and we are ready to merge it!

2020-03-19 20:36 UTC, closed without merging